export const GET_AIRLINE_PENDING = "GET_AIRLINE_PENDING"
export const GET_AIRLINE_SUCCESS = "GET_AIRLINE_SUCCESS"
export const GET_AIRLINE_FAILED = "GET_AIRLINE_FAILED"
export const GET_DETAIL_AIRLINE_PENDING = "GET_DETAIL_AIRLINE_PENDING";
export const GET_DETAIL_AIRLINE_SUCCESS = "GET_DETAIL_AIRLINE_SUCCESS";
export const GET_DETAIL_AIRLINE_FAILED = "GET_DETAIL_AIRLINE_FAILED";

export const GET_PRODUCT_PENDING = "GET_AIRLINE_PENDING"
export const GET_PRODUCT_SUCCESS = "GET_AIRLINE_SUCCESS"
export const GET_PRODUCT_FAILED = "GET_AIRLINE_FAILED"
export const GET_DETAIL_PRODUCT_PENDING = "GET_DETAIL_PRODUCT_PENDING";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAILED = "GET_DETAIL_PRODUCT_FAILED";